# Generated by Django 6.0.7 on 2026-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
